import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Autogenerated from docs/ (which points at the repository's real
  // docs/ folder, see docusaurus.config.ts) - ADRs and plan phases are
  // already numerically prefixed on disk, which Docusaurus respects for
  // ordering; docs/design/*.md files have no numeric prefix and sort
  // alphabetically, a deliberate choice over renaming files that dozens
  // of source comments elsewhere in the repo already reference by path.
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
