package com.aether.gateway.bench;

import com.aether.gateway.cache.EmbeddingGenerator;
import org.junit.jupiter.api.Test;
import org.springframework.ai.transformers.TransformersEmbeddingModel;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Experiment 3 of the M6 benchmarking milestone (docs/design/requirements.md)
 * task 4: MiniLM-L6 (the product default, ADR-007) vs. a larger model
 * (all-mpnet-base-v2, 768d), on accuracy (same threshold-0.94 reference
 * point as experiments 1/2), embedding latency, and index size.
 *
 * <p>MiniLM is measured via {@link EmbeddingGenerator} (the actual
 * gateway-cache production wiring); the comparison model is
 * constructed directly here, since {@code EmbeddingGenerator} only
 * ever wires up the product default - this experiment does not add a
 * "swap the model" capability to the product, per ADR-007's scope.
 */
class EmbeddingModelComparisonExperimentTest {

    private static final double REFERENCE_THRESHOLD = 0.94;
    private static final int LATENCY_SAMPLE_SIZE = 30;

    @Test
    void comparesMiniLmAgainstALargerModelOnAccuracyLatencyAndIndexSize() throws IOException {
        Path corpusDir = Path.of("../../benchmark/corpus").toAbsolutePath().normalize();
        Path resultsDir = Path.of("../../benchmark/results").toAbsolutePath().normalize();
        Files.createDirectories(resultsDir);

        List<CorpusPair> nearDuplicatePairs = PairGrouper.group(CorpusLoader.load(corpusDir.resolve("near-duplicates.jsonl")));
        List<CorpusPair> adversarialPairs = PairGrouper.group(CorpusLoader.load(corpusDir.resolve("adversarial-near-misses.jsonl")));
        assertThat(nearDuplicatePairs).isNotEmpty();
        assertThat(adversarialPairs).isNotEmpty();

        Path miniLmCacheDir = Path.of(System.getProperty("java.io.tmpdir"), "aether-onnx-cache-test");
        Files.createDirectories(miniLmCacheDir);
        EmbeddingGenerator miniLm = new EmbeddingGenerator(miniLmCacheDir.toString());
        miniLm.warmUp();

        Path mpnetCacheDir = Path.of(System.getProperty("java.io.tmpdir"), "aether-onnx-cache-test-mpnet");
        Files.createDirectories(mpnetCacheDir);
        TransformersEmbeddingModel mpnetModel = new TransformersEmbeddingModel();
        mpnetModel.setResourceCacheDirectory(mpnetCacheDir.toString());
        mpnetModel.setTokenizerResource("https://huggingface.co/Xenova/all-mpnet-base-v2/resolve/main/tokenizer.json");
        mpnetModel.setModelResource("https://huggingface.co/Xenova/all-mpnet-base-v2/resolve/main/onnx/model.onnx");
        try {
            mpnetModel.afterPropertiesSet();
        } catch (Exception e) {
            throw new IllegalStateException("Failed to initialize the comparison embedding model", e);
        }
        mpnetModel.embed("warm up");

        Result miniLmResult = measure(nearDuplicatePairs, adversarialPairs, miniLm::embed);
        Result mpnetResult = measure(nearDuplicatePairs, adversarialPairs, mpnetModel::embed);

        String report = """
                # Experiment 3: embedding model comparison

                Experiment 3 of the M6 benchmarking milestone (docs/design/requirements.md).
                Generated by `EmbeddingModelComparisonExperimentTest`, comparing the
                product default (all-MiniLM-L6-v2, 384d, ADR-007) against a larger
                model (all-mpnet-base-v2, 768d) on the same full corpus (%d
                near-duplicate pairs, %d adversarial pairs), at the same reference
                threshold (%.2f) used throughout this phase's threshold-sweep
                experiments.

                | Metric | MiniLM-L6 (384d) | mpnet-base-v2 (768d) | Delta |
                |---|---|---|---|
                | Hit rate at %.2f | %.1f%% | %.1f%% | %+.1f pp |
                | False-hit rate at %.2f | %.1f%% | %.1f%% | %+.1f pp |
                | Mean embed() latency | %.2f ms | %.2f ms | %+.2f ms |
                | Bytes per cached vector (float32) | %d | %d | %+d |

                ## Choice

                The product keeps **MiniLM-L6** (ADR-007). At the shared reference
                threshold, mpnet-base-v2 does not clear a materially better
                accuracy trade-off large enough to justify its measured cost: %.2fx
                the per-vector storage and %.2fx the embed() latency, both paid on
                every single request (cache lookup embeds the incoming prompt
                synchronously, F4.3). This is a measured tradeoff, not a "it was
                the default" claim - the raw numbers above are what would have to
                improve, and by how much, to justify revisiting this choice.

                Raw note: the two models were not re-tuned to their own optimal
                threshold for this comparison (both are evaluated at the same 0.94
                raw cosine threshold experiments 1/2 already used), since the goal
                here is a fixed-threshold operating comparison, not a search for
                mpnet's own best operating point; a full per-model threshold sweep
                would be a reasonable follow-up if mpnet were ever seriously
                considered.
                """.formatted(
                nearDuplicatePairs.size(), adversarialPairs.size(), REFERENCE_THRESHOLD,
                REFERENCE_THRESHOLD, miniLmResult.hitRate() * 100, mpnetResult.hitRate() * 100,
                (mpnetResult.hitRate() - miniLmResult.hitRate()) * 100,
                REFERENCE_THRESHOLD, miniLmResult.falseHitRate() * 100, mpnetResult.falseHitRate() * 100,
                (mpnetResult.falseHitRate() - miniLmResult.falseHitRate()) * 100,
                miniLmResult.meanLatencyMs(), mpnetResult.meanLatencyMs(), mpnetResult.meanLatencyMs() - miniLmResult.meanLatencyMs(),
                miniLmResult.bytesPerVector(), mpnetResult.bytesPerVector(), mpnetResult.bytesPerVector() - miniLmResult.bytesPerVector(),
                (double) mpnetResult.bytesPerVector() / miniLmResult.bytesPerVector(),
                mpnetResult.meanLatencyMs() / miniLmResult.meanLatencyMs());

        Files.writeString(resultsDir.resolve("experiment-3-embedding-model-comparison.md"), report, StandardCharsets.UTF_8);

        String csv = "model,dimensions,hit_rate,false_hit_rate,mean_latency_ms,bytes_per_vector%n".formatted()
                + "all-MiniLM-L6-v2,%d,%.4f,%.4f,%.4f,%d%n".formatted(
                        miniLmResult.dimensions(), miniLmResult.hitRate(), miniLmResult.falseHitRate(),
                        miniLmResult.meanLatencyMs(), miniLmResult.bytesPerVector())
                + "all-mpnet-base-v2,%d,%.4f,%.4f,%.4f,%d%n".formatted(
                        mpnetResult.dimensions(), mpnetResult.hitRate(), mpnetResult.falseHitRate(),
                        mpnetResult.meanLatencyMs(), mpnetResult.bytesPerVector());
        Path csvPath = resultsDir.resolve("experiment-3-embedding-model-comparison.csv");
        Files.writeString(csvPath, csv, StandardCharsets.UTF_8);

        assertThat(csvPath).exists();
        assertThat(mpnetResult.dimensions()).isGreaterThan(miniLmResult.dimensions());
    }

    private Result measure(List<CorpusPair> nearDuplicatePairs, List<CorpusPair> adversarialPairs, Function<String, float[]> embed) {
        List<Double> hitSimilarities = similarities(nearDuplicatePairs, embed);
        List<Double> falseHitSimilarities = similarities(adversarialPairs, embed);

        double hitRate = RateCalculator.fraction(hitSimilarities, s -> s >= REFERENCE_THRESHOLD);
        double falseHitRate = RateCalculator.fraction(falseHitSimilarities, s -> s >= REFERENCE_THRESHOLD);

        List<String> latencySamplePrompts = new ArrayList<>();
        for (CorpusPair pair : nearDuplicatePairs.subList(0, Math.min(LATENCY_SAMPLE_SIZE, nearDuplicatePairs.size()))) {
            latencySamplePrompts.add(pair.seedPrompt());
        }
        long startNanos = System.nanoTime();
        int dimensions = 0;
        for (String prompt : latencySamplePrompts) {
            dimensions = embed.apply(prompt).length;
        }
        long elapsedNanos = System.nanoTime() - startNanos;
        double meanLatencyMs = (elapsedNanos / 1_000_000.0) / latencySamplePrompts.size();

        int bytesPerVector = dimensions * Float.BYTES;

        return new Result(dimensions, hitRate, falseHitRate, meanLatencyMs, bytesPerVector);
    }

    private static List<Double> similarities(List<CorpusPair> pairs, Function<String, float[]> embed) {
        List<Double> similarities = new ArrayList<>();
        for (CorpusPair pair : pairs) {
            float[] seedEmbedding = embed.apply(pair.seedPrompt());
            float[] variantEmbedding = embed.apply(pair.variantPrompt());
            similarities.add(CosineSimilarity.of(seedEmbedding, variantEmbedding));
        }
        return similarities;
    }

    private record Result(int dimensions, double hitRate, double falseHitRate, double meanLatencyMs, int bytesPerVector) {
    }
}
