package com.aether.gateway.bench;

import com.aether.gateway.cache.EmbeddingGenerator;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * PRD section 16.2, experiment 1 / docs/plan/09-milestone-m6-benchmarking.md
 * task 2: the full 0.80-0.99-in-0.01-steps threshold sweep against the
 * real embedding model and the full labelled near-duplicate and
 * adversarial buckets (no guard - that is experiment 2's job). Produces
 * the precision/recall curve `BENCHMARKS.md` will cite.
 */
class ThresholdSweepExperimentTest {

    private static final List<Double> THRESHOLDS = thresholds();

    @Test
    void sweepsFineGrainedThresholdsAgainstTheFullCorpusAndWritesTheCsv() throws IOException {
        Path corpusDir = Path.of("../../benchmark/corpus").toAbsolutePath().normalize();
        Path resultsDir = Path.of("../../benchmark/results").toAbsolutePath().normalize();
        Files.createDirectories(resultsDir);

        List<CorpusPair> nearDuplicatePairs = PairGrouper.group(CorpusLoader.load(corpusDir.resolve("near-duplicates.jsonl")));
        List<CorpusPair> adversarialPairs = PairGrouper.group(CorpusLoader.load(corpusDir.resolve("adversarial-near-misses.jsonl")));
        assertThat(nearDuplicatePairs).isNotEmpty();
        assertThat(adversarialPairs).isNotEmpty();

        Path cacheDir = Path.of(System.getProperty("java.io.tmpdir"), "aether-onnx-cache-test");
        Files.createDirectories(cacheDir);
        EmbeddingGenerator embeddingGenerator = new EmbeddingGenerator(cacheDir.toString());
        embeddingGenerator.warmUp();

        List<Double> hitSimilarities = similarities(nearDuplicatePairs, embeddingGenerator);
        List<Double> falseHitSimilarities = similarities(adversarialPairs, embeddingGenerator);

        StringBuilder csv = new StringBuilder("threshold,hit_rate,false_hit_rate\n");
        List<Double> hitRates = new ArrayList<>();
        List<Double> falseHitRates = new ArrayList<>();
        double previousHitRate = Double.POSITIVE_INFINITY;
        double bestThreshold = THRESHOLDS.get(THRESHOLDS.size() - 1);
        double bestHitRate = 0;
        double bestFalseHitRate = 1;
        double hitRateFloor = 0.10;
        double lowestFalseHitRateAtOrAboveFloor = Double.MAX_VALUE;
        for (double threshold : THRESHOLDS) {
            double hitRate = RateCalculator.fraction(hitSimilarities, s -> s >= threshold);
            double falseHitRate = RateCalculator.fraction(falseHitSimilarities, s -> s >= threshold);

            // Sanity: raising the threshold can only ever exclude more
            // candidates, never admit new ones, so hit rate must be
            // monotonically non-increasing as threshold rises.
            assertThat(hitRate).isLessThanOrEqualTo(previousHitRate);
            previousHitRate = hitRate;

            hitRates.add(hitRate);
            falseHitRates.add(falseHitRate);
            csv.append(String.format(Locale.ROOT, "%.2f,%.4f,%.4f%n", threshold, hitRate, falseHitRate));

            if (hitRate >= hitRateFloor && falseHitRate < lowestFalseHitRateAtOrAboveFloor) {
                lowestFalseHitRateAtOrAboveFloor = falseHitRate;
                bestThreshold = threshold;
                bestHitRate = hitRate;
                bestFalseHitRate = falseHitRate;
            }
        }

        Path csvPath = resultsDir.resolve("experiment-1-threshold-sweep.csv");
        Files.writeString(csvPath, csv.toString(), StandardCharsets.UTF_8);

        Map<String, List<Double>> series = new LinkedHashMap<>();
        series.put("hit rate (near-duplicates)", hitRates);
        series.put("false-hit rate (adversarial)", falseHitRates);
        String svg = SvgLineChart.render("Experiment 1: threshold sweep (0.80-0.99), no entity guard", THRESHOLDS, series);
        Path svgPath = resultsDir.resolve("experiment-1-threshold-sweep.svg");
        Files.writeString(svgPath, svg, StandardCharsets.UTF_8);

        String report = """
                # Experiment 1: threshold sweep

                PRD section 16.2(1) / docs/plan/09-milestone-m6-benchmarking.md task 2.
                Generated by `ThresholdSweepExperimentTest`, against the real
                all-MiniLM-L6-v2 embedding model and the full labelled corpus
                (%d near-duplicate pairs, %d adversarial pairs) - no mocking of
                either. No entity guard applied here (that ablation is
                experiment 2); this is the raw embedding-similarity
                precision/recall curve.

                ![threshold sweep chart](experiment-1-threshold-sweep.svg)

                Raw data: `experiment-1-threshold-sweep.csv`.

                ## Chosen raw operating point (pre-guard)

                **threshold = %.2f**, hit rate %.1f%%, false-hit rate %.1f%% \
                (no guard).

                Justification: among thresholds that keep the cache \
                meaningfully useful (hit rate >= %.0f%%, a floor only to \
                exclude degenerate near-zero-hit-rate points), this is the \
                one that minimises the raw false-hit rate - the Pareto-best \
                point actually measured on the full corpus. This is a \
                *pre-guard* reference point only: the entity/numeric guard \
                (experiment 2) changes the false-hit side of this trade-off \
                substantially and is the deciding factor for the final \
                production threshold, matching Phase 07's own finding that \
                every swept threshold has a nonzero false-hit rate without \
                the guard active.
                """.formatted(
                nearDuplicatePairs.size(), adversarialPairs.size(),
                bestThreshold, bestHitRate * 100, bestFalseHitRate * 100, hitRateFloor * 100);

        Path reportPath = resultsDir.resolve("experiment-1-threshold-sweep.md");
        Files.writeString(reportPath, report, StandardCharsets.UTF_8);

        assertThat(csvPath).exists();
        assertThat(Files.readAllLines(csvPath)).hasSize(THRESHOLDS.size() + 1);
        assertThat(bestHitRate).as("at least one swept threshold must achieve a nonzero measured hit rate").isGreaterThan(0);
    }

    private static List<Double> similarities(List<CorpusPair> pairs, EmbeddingGenerator embeddingGenerator) {
        List<Double> similarities = new ArrayList<>();
        for (CorpusPair pair : pairs) {
            float[] seedEmbedding = embeddingGenerator.embed(pair.seedPrompt());
            float[] variantEmbedding = embeddingGenerator.embed(pair.variantPrompt());
            similarities.add(CosineSimilarity.of(seedEmbedding, variantEmbedding));
        }
        return similarities;
    }

    private static List<Double> thresholds() {
        List<Double> values = new ArrayList<>();
        for (int hundredths = 80; hundredths <= 99; hundredths++) {
            values.add(hundredths / 100.0);
        }
        return values;
    }
}
