package com.aether.gateway.cache;

import com.aether.gateway.core.domain.EntityNumericGuard;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Phase 07 (M4) task 12 / exit criterion: "Hit rate and false-hit rate
 * measured on the 500-prompt corpus." Runs the real embedding model
 * against the real near-duplicate and adversarial buckets (no mocking
 * of either the model or the corpus), sweeps a representative set of
 * candidate thresholds, and writes a report with the chosen operating
 * point and its justification. This is *not* the full 0.80-0.99-in-0.01
 * -steps sweep with plots (that is Phase 09's job per the plan); it is
 * the one real sweep this phase's exit criterion requires so the
 * threshold is measured, not guessed.
 */
class ThresholdSweepTest {

    private static final double[] CANDIDATE_THRESHOLDS = {0.75, 0.80, 0.85, 0.88, 0.90, 0.92, 0.94, 0.96, 0.98};

    @Test
    void sweepsThresholdsAgainstTheRealCorpusAndWritesAReport() throws IOException {
        Path corpusDir = Path.of("../../benchmark/corpus").toAbsolutePath().normalize();
        Path resultsDir = Path.of("../../benchmark/results").toAbsolutePath().normalize();
        Files.createDirectories(resultsDir);

        List<Pair> nearDuplicates = loadPairs(corpusDir.resolve("near-duplicates.jsonl"));
        List<Pair> adversarial = loadPairs(corpusDir.resolve("adversarial-near-misses.jsonl"));
        assertThat(nearDuplicates).isNotEmpty();
        assertThat(adversarial).isNotEmpty();

        Path cacheDir = Path.of(System.getProperty("java.io.tmpdir"), "aether-onnx-cache-test");
        Files.createDirectories(cacheDir);
        var embeddingGenerator = new EmbeddingGenerator(cacheDir.toString());
        embeddingGenerator.warmUp();

        List<Measurement> ndMeasurements = measure(nearDuplicates, embeddingGenerator);
        List<Measurement> advMeasurements = measure(adversarial, embeddingGenerator);

        StringBuilder report = new StringBuilder();
        report.append("# M4 threshold sweep results\n\n");
        report.append("Generated by `ThresholdSweepTest`, against the real all-MiniLM-L6-v2 embedding model ")
                .append("and the real corpus (no mocking of either). Not the full Phase 09 experiment suite - ")
                .append("see docs/plan/07-milestone-m4-semantic-cache.md task 12 and docs/design/cache-correctness.md.\n\n");
        report.append("- Near-duplicate pairs measured: ").append(ndMeasurements.size()).append("\n");
        report.append("- Adversarial pairs measured: ").append(advMeasurements.size()).append("\n\n");

        report.append("| Threshold | Hit rate (near-dup) | False-hit rate, no guard | False-hit rate, with guard |\n");
        report.append("|---|---|---|---|\n");

        // Operating-point choice: no swept threshold reaches a 0%
        // guarded false-hit rate (see "Residual false-hit analysis"
        // below for why), so the naive rule "pick the threshold where
        // false-hits hit zero" never fires. Instead: among thresholds
        // that keep the cache meaningfully useful (hit rate >= a 10%
        // floor - deliberately low, only to rule out near-zero-hit-rate
        // degenerate points, not a target in itself), pick the one that
        // minimises the guarded false-hit rate. This is a Pareto choice
        // computed from the actual measured trade-off, not a guess.
        double hitRateFloor = 0.10;
        double bestThreshold = CANDIDATE_THRESHOLDS[CANDIDATE_THRESHOLDS.length - 1];
        double bestGuardedFalseHitRate = Double.MAX_VALUE;
        double bestHitRate = 0;
        for (double threshold : CANDIDATE_THRESHOLDS) {
            double hitRate = fraction(ndMeasurements, m -> m.similarity() >= threshold);
            double rawFalseHitRate = fraction(advMeasurements, m -> m.similarity() >= threshold);
            double guardedFalseHitRate = fraction(advMeasurements, m -> m.similarity() >= threshold && m.guardWouldAllow());

            report.append(String.format(Locale.ROOT, "| %.2f | %.1f%% | %.1f%% | %.1f%% |%n",
                    threshold, hitRate * 100, rawFalseHitRate * 100, guardedFalseHitRate * 100));

            if (hitRate >= hitRateFloor && guardedFalseHitRate < bestGuardedFalseHitRate) {
                bestGuardedFalseHitRate = guardedFalseHitRate;
                bestThreshold = threshold;
                bestHitRate = hitRate;
            }
        }

        report.append("\n## Chosen operating point\n\n");
        report.append(String.format(Locale.ROOT, "**threshold = %.2f**, measured hit rate %.1f%%, measured false-hit rate %.1f%% with the entity guard active.%n%n",
                bestThreshold, bestHitRate * 100, bestGuardedFalseHitRate * 100));
        report.append("Justification: among the candidate thresholds that keep the cache meaningfully useful ")
                .append("(hit rate >= 10%, a floor only to exclude degenerate near-zero-hit-rate points), this is the ")
                .append("one that minimises the guarded false-hit rate - the Pareto-best point actually measured, not ")
                .append("a guess. It does not yet clear AC3 (hit rate >= 35%) or AC4 (false-hit rate <= 5%) ")
                .append("simultaneously; per this phase's plan, that is acceptable as long as the numbers are measured ")
                .append("and the choice is justified, with further tuning left to Phase 09's full experiment suite.\n\n")
                .append("**Residual false-hit analysis.** At every threshold swept, the guarded false-hit rate is ")
                .append("strictly greater than zero. Inspecting the corpus explains why: the entity/numeric guard ")
                .append("(EntityNumericGuard) only ever compares extracted numbers, named entities, and dates, exactly ")
                .append("as F4's correctness note specifies - it has no concept of negation or polarity. Several ")
                .append("adversarial pairs in the corpus change meaning through negation or a direction flip alone ")
                .append("(\"is open\" vs \"is closed\", \"rose\" vs \"fell\", \"increased\" vs \"decreased\", ")
                .append("\"expected\" vs \"not expected\") with no number, entity, or date changing at all; these are, ")
                .append("by the guard's defined scope, structurally undetectable by it and will pass through as a hit ")
                .append("whenever their embedding similarity clears the threshold. This is a genuine, documented ")
                .append("limitation, not a bug - closing it would mean extending the guard beyond what F4 specifies ")
                .append("(e.g. a small negation-word check), which is a reasonable Phase 09 follow-up, not required ")
                .append("for this phase's exit criterion.\n");

        Files.writeString(resultsDir.resolve("m4-threshold-sweep.md"), report.toString(), StandardCharsets.UTF_8);
        System.out.println(report);

        assertThat(bestHitRate).as("at least one swept threshold must achieve a nonzero measured hit rate").isGreaterThan(0);
    }

    private double fraction(List<Measurement> measurements, java.util.function.Predicate<Measurement> predicate) {
        if (measurements.isEmpty()) {
            return 0.0;
        }
        long count = measurements.stream().filter(predicate).count();
        return (double) count / measurements.size();
    }

    private List<Measurement> measure(List<Pair> pairs, EmbeddingGenerator embeddingGenerator) {
        List<Measurement> results = new ArrayList<>();
        for (Pair pair : pairs) {
            float[] seedEmbedding = embeddingGenerator.embed(pair.seed());
            float[] variantEmbedding = embeddingGenerator.embed(pair.variant());
            double similarity = cosineSimilarity(seedEmbedding, variantEmbedding);
            boolean guardWouldAllow = EntityNumericGuard.sameFingerprint(pair.seed(), pair.variant());
            results.add(new Measurement(pair, similarity, guardWouldAllow));
        }
        return results;
    }

    private double cosineSimilarity(float[] a, float[] b) {
        double dot = 0;
        double normA = 0;
        double normB = 0;
        for (int i = 0; i < a.length; i++) {
            dot += a[i] * b[i];
            normA += a[i] * a[i];
            normB += b[i] * b[i];
        }
        return dot / (Math.sqrt(normA) * Math.sqrt(normB));
    }

    private record Pair(String pairId, String seed, String variant) {
    }

    private record Measurement(Pair pair, double similarity, boolean guardWouldAllow) {
    }

    private List<Pair> loadPairs(Path jsonlFile) throws IOException {
        JsonMapper mapper = JsonMapper.builder().build();
        Map<String, String> seeds = new LinkedHashMap<>();
        Map<String, String> variants = new LinkedHashMap<>();
        List<String> order = new ArrayList<>();

        for (String line : Files.readAllLines(jsonlFile, StandardCharsets.UTF_8)) {
            if (line.isBlank()) {
                continue;
            }
            JsonNode node = mapper.readTree(line);
            String pairId = node.path("pair_id").asString(null);
            if (pairId == null) {
                continue; // unrelated/long-context style entries have no pair_id
            }
            String role = node.path("role").asString("");
            String prompt = node.path("prompt").asString("");
            if ("seed".equals(role)) {
                seeds.put(pairId, prompt);
                order.add(pairId);
            } else if ("variant".equals(role)) {
                variants.put(pairId, prompt);
            }
        }

        List<Pair> pairs = new ArrayList<>();
        for (String pairId : order) {
            if (seeds.containsKey(pairId) && variants.containsKey(pairId)) {
                pairs.add(new Pair(pairId, seeds.get(pairId), variants.get(pairId)));
            }
        }
        return pairs;
    }
}
